<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Crypt;

class FournisseursTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('fournisseurs')->insert([
            'id' => '1',
            'name'=> 'Rona Inc Trois-Rivieres',
            'address' => '4025 Boulevard des Récollets',
            'city' => 'Trois-Rivières',
            'province' => 'Québec',
            'region' => 'Mauricie (04)',
            'country' => 'Canada',
            'phone' => json_encode(['8196930855', 'Bureau']),
            'postCode' => 'g9a6m1',
            'unspsc' => json_encode(['31160000','25101702']),
            'website' => 'rona.ca',
            'email' => 'rona@rona.ca',
            'files' => json_encode(['']),
            'neq' => '1171854699',
            'rbq' => '',
            'typesRbq' => json_encode(['1.1', '1.2']),
            'password' => Hash::make('rona'),
            'raisonRefus' => null,
            'personneContact' => json_encode('Directeur'),
            'statut'=> 'A',
        ]);

        DB::table('fournisseurs')->insert([
            'id' => '2',
            'name'=> 'Ford Canada',
            'address' => '1 The Canadian Road',
            'city' => 'Oakville',
            'province' => 'Ontario',
            'country' => 'Canada',
            'phone' => json_encode(['18005653673', 'Bureau']),
            'postCode' => 'L6J5E4',
            'unspsc' => json_encode(['25101702']),
            'website' => 'ford.ca',
            'email' => 'ford@ford.ca',
            'files' => json_encode(['']),
            'neq' => '1146438586',
            'rbq' => '',
            'typesRbq' => json_encode(['1.3', '1.2']),
            'password' => Hash::make('ford'),
            'raisonRefus' => null,
            'personneContact' => json_encode('Directeur'),
            'statut'=> 'A',

        ]);

        DB::table('fournisseurs')->insert([
            'id' => '3',
            'name' => 'Manoir de l\'Aube Inc.',
            'address' => '1035 av. Holland',
            'city' => 'Québec',
            'province' => 'Québec',
            'region' => 'Capitale-Nationale (03)',
            'country' => 'Canada',
            'phone' => json_encode(['18005653673', 'Bureau']),
            'postCode' => 'G1S3T4',
            'unspsc' => json_encode([
                '42293122', '42293123', '42293124', '42293125',
                '39121520', '39121521', '39121522', '39121523', '39121524'
            ]),
            'website' => 'www.manoirdelaubeinc.com',
            'email' => 'info@manoirdelaubeinc.com',
            'files' => json_encode(['']),
            'neq' => '1140087702',
            'rbq' => '',
            'typesRbq' => json_encode(['1.4', '1.5']),
            'password' => Hash::make('Abc%123'),
            'raisonRefus' => null,
            'personneContact' => json_encode('Clement Désilets'),
            'statut' => 'A',
        ]);
        
        DB::table('fournisseurs')->insert([
            'id' => '4',
            'name' => 'Lobe Réseau Inc.',
            'address' => '14640 BOUL. Lacroix',
            'city' => 'Saint-Georges',
            'province' => 'Québec',
            'region' => 'Chaudière-Appalaches (12)',
            'country' => 'Canada',
            'phone' => json_encode(['4186409293', 'Bureau']),
            'postCode' => 'G5Y7G8',
            'unspsc' => json_encode([
                '80111708', '80111709', '80111710',
                '48101816', '48101817', '48101818',
                '48101819', '48101820'
            ]),
            'website' => 'www.loberéseauinc.com',
            'email' => 'info@loberéseauinc.com',
            'files' => json_encode(['']),
            'neq' => '1140091761',
            'rbq' => '',
            'typesRbq' => json_encode(['1.6', '1.7']),
            'password' => Hash::make('Abc%123'),
            'raisonRefus' => null,
            'personneContact' => json_encode('Phoebe Maltais'),
            'statut' => 'A',
        ]);
        
        DB::table('fournisseurs')->insert([
            'id' => '5',
            'name' => 'Dépanneur N.C. Inc.',
            'address' => '5000 boul. de l\'Ormière',
            'city' => 'Québec',
            'province' => 'Québec',
            'region' => 'Capitale-Nationale (03)',
            'country' => 'Canada',
            'phone' => json_encode(['18005653673', 'Bureau']),
            'postCode' => 'G1P1K7',
            'unspsc' => json_encode([
                '48101801', '48101802', '48101803', '48101804', '48101805'
            ]),
            'website' => 'www.dépanneurncinc.com',
            'email' => 'info@dépanneurncinc.com',
            'files' => json_encode(['']),
            'neq' => '1140093601',
            'rbq' => '',
            'typesRbq' => json_encode(['1.1', '1.2']),
            'password' => Hash::make('Abc%123'),
            'raisonRefus' => null,
            'personneContact' => json_encode('Miro Petit'),
            'statut' => 'A',
        ]);
        
        DB::table('fournisseurs')->insert([
            'id' => '6',
            'name'=> 'Gestion Gota Inc.',
            'address' => '5838 rue de la Frontière',
            'city' => 'Sherbrooke',
            'province' => 'Québec',
            'region' => 'Estrie (05)',
            'country' => 'Canada',
            'phone' => json_encode(['4385034820', 'Bureau']),
            'postCode' => 'J1N3X2',
            'unspsc' => json_encode(['25172802', '25172803', '42201703', '42201704', '42201705', '42201706']),
            'website' => 'www.gestiongotainc.com',
            'email' => 'info@gestiongotainc.com',
            'files' => json_encode(['']),
            'neq' => '1140259889',
            'rbq' => '',
            'typesRbq' => json_encode(['1.1', '1.2', '1.3']),
            'password' => Hash::make('Abc%123'),
            'raisonRefus' => null,
            'personneContact' => json_encode('Joud Kirouac'),
            'statut'=> 'R',
        ]);
        
        DB::table('fournisseurs')->insert([
            'id' => '7',
            'name'=> 'Restaurant Pierrette Patate',
            'address' => '3900 rue de Verdun',
            'city' => 'Montréal',
            'province' => 'Québec',
            'region' => 'Montréal (06)',
            'country' => 'Canada',
            'phone' => json_encode(['5794906641', 'Bureau']),
            'postCode' => 'H4G1K9',
            'unspsc' => json_encode(['41113031', '41113032', '41113033', '42312111', '42312112', '42312113', '41113624', '41113625']),
            'website' => 'www.restaurantpierrettepatate.com',
            'email' => 'info@restaurantpierrettepatate.com',
            'files' => json_encode(['']),
            'neq' => '1140264004',
            'rbq' => '',
            'typesRbq' => json_encode(['1.1', '1.4', '1.5']),
            'password' => Hash::make('Abc%123'),
            'raisonRefus' => null,
            'personneContact' => json_encode('Rose Munger'),
            'statut'=> 'AT',
        ]);
        
        DB::table('fournisseurs')->insert([
            'id' => '8',
            'name'=> 'Centre de la Petite Enfance Les Petits Cailloux Installation Bégin',
            'address' => '130A rue Brassard',
            'city' => 'Bégin',
            'province' => 'Québec',
            'region' => 'Saguenay--Lac-Saint-Jean (02)',
            'country' => 'Canada',
            'phone' => json_encode(['5817979493', 'Bureau']),
            'postCode' => 'G0V1B0',
            'unspsc' => json_encode(['31161612', '31161613', '23101514', '23101515']),
            'website' => 'www.centredelapetiteenfanceles.com',
            'email' => 'info@centredelapetiteenfanceles.com',
            'files' => json_encode(['']),
            'neq' => '1140285694',
            'rbq' => '',
            'typesRbq' => json_encode(['1.2', '1.6']),
            'password' => Hash::make('Abc%123'),
            'raisonRefus' => null,
            'personneContact' => json_encode('Norah Bouchard'),
            'statut'=> 'AT',
        ]);
        
        DB::table('fournisseurs')->insert([
            'id' => '9',
            'name'=> 'Rock-N-C Resto-Bar Enr.',
            'address' => 'N/A',
            'city' => 'N/A',
            'province' => 'Québec',
            'region' => 'Montréal (06)',
            'country' => 'Canada',
            'phone' => json_encode(['N/A', 'Bureau']),
            'postCode' => 'N/A',
            'unspsc' => json_encode(['41113624', '41113625']),
            'website' => 'www.rockncrestobarenr.com',
            'email' => 'info@rockncrestobarenr.com',
            'files' => json_encode(['']),
            'neq' => '1140296907',
            'rbq' => '',
            'typesRbq' => json_encode(['1.1', '1.8']),
            'password' => Hash::make('Abc%123'),
            'raisonRefus' => null,
            'personneContact' => json_encode('N/A'),
            'statut'=> 'AT',
        ]);
        
        DB::table('fournisseurs')->insert([
            'id' => '10',
            'name'=> 'Ventes et Services Technologiques Inc.',
            'address' => '1020 rue de la Technologie',
            'city' => 'Québec',
            'province' => 'Québec',
            'region' => 'Capitale-Nationale (03)',
            'country' => 'Canada',
            'phone' => json_encode(['4185552931', 'Bureau']),
            'postCode' => 'G1X4N5',
            'unspsc' => json_encode(['43211501', '43211502', '43211600']),
            'website' => 'vstinc.ca',
            'email' => 'contact@vstinc.ca',
            'files' => json_encode(['']),
            'neq' => '1140401234',
            'rbq' => '',
            'typesRbq' => json_encode(['1.1']),
            'password' => Hash::make('Vst1234%'),
            'raisonRefus' => null,
            'personneContact' => json_encode('Responsable Des Ventes'),
            'statut'=> 'A',
        ]);
        
        DB::table('fournisseurs')->insert([
            'id' => '11',
            'name'=> 'Équipement Automatique Aventure',
            'address' => '58 rue des Industries',
            'city' => 'Trois-Rivières',
            'province' => 'Québec',
            'region' => 'Mauricie (04)',
            'country' => 'Canada',
            'phone' => json_encode(['8196964523', 'Bureau']),
            'postCode' => 'G9A1J4',
            'unspsc' => json_encode(['25171600', '25171601', '25171602']),
            'website' => 'equipautoaventure.com',
            'email' => 'service@equipautoaventure.com',
            'files' => json_encode(['']),
            'neq' => '1140426783',
            'rbq' => '',
            'typesRbq' => json_encode(['1.1']),
            'password' => Hash::make('Auto1234%'),
            'raisonRefus' => null,
            'personneContact' => json_encode('Technicien Principal'),
            'statut'=> 'A',
        ]);
        
        DB::table('fournisseurs')->insert([
            'id' => '12',
            'name'=> 'Solutions Environnementales Lavoie',
            'address' => '1500 rue Principale',
            'city' => 'Gatineau',
            'province' => 'Québec',
            'region' => 'Outaouais (08)',
            'country' => 'Canada',
            'phone' => json_encode(['8197703212', 'Bureau']),
            'postCode' => 'J8X4B9',
            'unspsc' => json_encode(['77101501', '77101502', '77101503']),
            'website' => 'solutionslavoie.com',
            'email' => 'info@solutionslavoie.com',
            'files' => json_encode(['']),
            'neq' => '1140450192',
            'rbq' => '',
            'typesRbq' => json_encode(['1.1', '1.2']),
            'password' => Hash::make('Enviro1234%'),
            'raisonRefus' => null,
            'personneContact' => json_encode('Coordonateur Des Projets'),
            'statut'=> 'AR',
        ]);
        
        DB::table('fournisseurs')->insert([
            'id' => '13',
            'name'=> 'Réseau Sécuritaire de l\'Est',
            'address' => '205 rue de la Sécurité',
            'city' => 'Longueuil',
            'province' => 'Québec',
            'region' => 'Montérégie (10)',
            'country' => 'Canada',
            'phone' => json_encode(['4504635684', 'Bureau']),
            'postCode' => 'J4H3A5',
            'unspsc' => json_encode(['46171500', '46171501']),
            'website' => 'reseausecuritaireest.com',
            'email' => 'contact@reseausecuritaireest.com',
            'files' => json_encode(['']),
            'neq' => '1140471506',
            'rbq' => '',
            'typesRbq' => json_encode(['1.1']),
            'password' => Hash::make('Securite1234%'),
            'raisonRefus' => null,
            'personneContact' => json_encode('Directeur des Opérations'),
            'statut'=> 'AT',
        ]);
        
        DB::table('fournisseurs')->insert([
            'id' => '14',
            'name'=> 'Technologies Lumos',
            'address' => '900 rue des Étoiles',
            'city' => 'Boucherville',
            'province' => 'Québec',
            'region' => 'Montérégie (10)',
            'country' => 'Canada',
            'phone' => json_encode(['4506557420', 'Bureau']),
            'postCode' => 'J4B2X6',
            'unspsc' => json_encode(['43222100', '43222200', '43222300']),
            'website' => 'lumos-technologies.com',
            'email' => 'info@lumos-technologies.com',
            'files' => json_encode(['']),
            'neq' => '1140493173',
            'rbq' => '',
            'typesRbq' => json_encode(['1.1']),
            'password' => Hash::make('Lumos1234%'),
            'raisonRefus' => null,
            'personneContact' => json_encode('Chef de Produit'),
            'statut'=> 'R',
        ]);
        
      
    }
}
